version: '3'

services:
  spark-capital:
    # image: spark-capital
    build: 
      context: .
      dockerfile: "Dockerfile.spark"
    container_name: hello-spark-capial
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8080:80"
    volumes: 
      - .:/app-1
    depends_on:
      - sqlite3