version: '3'

services:
  app:
    build: .
    images: "app:project-spark"
    ports:
      - "80:80"
    depends_on:
      - sqlite3
    # environment:
    #   - MYSQL_HOST=db
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=example_password
    #   - MYSQL_DB=example_db
    command: uvicorn main:app --host 0.0.0.0 --port 80

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  
  # db:
  #   image: mysql:latest
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=example_password
  #     - MYSQL_DATABASE=example_db