version: '3'

services:
  api:
    build: .
    ports:
      - "80:80"
    container_name: fastapi-application
    depends_on:
      - sqlite3
    restart: "no"
# services:
#   app:
#     build: .
#       dockerfile:"Dockerfile.spark"
#     images: "project-spark:${TAG}"
#     ports:
#       - "80:80"
#     depends_on:
#       - sqlite3
#     command: uvicorn main:app --host 0.0.0.0 --port 80

#   sqlite3:
#     image: nouchka/sqlite3:latest
#     stdin_open: true
#     tty: true
#     volumes:
#       - ./db/:/root/db/
  
  # db:
  #   image: mysql:latest
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=example_password
  #     - MYSQL_DATABASE=example_db